# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
project: BRICS
title: BRICS - Bit Flip Resilience for In-Memory Column Stores
title_short: Bit Flip Resilience for In-Memory Column Stores
email: till.kolditz@tu-dresden.de
description: >- # this means to ignore newlines until "baseurl:"
  Research project on detecting and correcting transient hardware errors
  (bit flips) during query processing in main-memory-centric database
  systems (especially, column stores).
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/images/logo_BRICS.png
logo_short: /assets/images/logo_BRICS_short.png
url: "https://brics-db.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  brics-db
project_url: "https://github.com/brics-db"

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
