theme: jekyll-theme-modernist
title: BRICS &ndash; Bit Flip Resilience for In-Memory Column Stores
description: Research project on detecting and correcting transient hardware errors (bit flips) during query processing in main-memory-centric database systems (especially, column stores).
